#!/usr/bin/env bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

g++ -o game \
        src/client/*.cpp \
        src/client/models/*.cpp \
        src/shared/*.cpp \
        external/lodepng/lodepng.cpp \
    -Iexternal/lodepng \
    -Iexternal/glm \
    -std=c++14 \
    -lstdc++ \
    -lglfw \
    -framework OpenGL

./game
