#!/usr/bin/env bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

cc -o game \
        src/*.cc \
        src/models/*.cc \
        external/lodepng/*.cc \
    -Iexternal/lodepng \
    -std=c++14 \
    -lstdc++ \
    -lglfw \
    -lpng \
    -framework OpenGL

./game
