#!/usr/bin/env bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

compile_cmd() {
    echo -e "\tcc -c -o \"$2\" $1 \\
        -Iexternal/lodepng \\
        -Iexternal/glm \\
        -Iexternal/tinyxml2 \\
        -std=c++14"
}

cpp_to_obj() {
    echo "$1" | sed 's/cpp$/o/;s:/:_:g'
}

make_cmd() {
    local obj_file="$(cpp_to_obj "$1")"
    cc -MM -MT "$obj_file" -c "$1" \
        -Iexternal/lodepng \
        -Iexternal/glm \
        -Iexternal/tinyxml2 \
        -std=c++14
    compile_cmd "$1" "$obj_file"
}

file_list() {
    find src/client src/shared -iname '*.cpp'
    echo external/lodepng/lodepng.cpp
    echo external/tinyxml2/tinyxml2.cpp
}

print_makefile() {
    local all=''
    for f in $(file_list); do
        all="$all $(cpp_to_obj $f)"
    done
    echo "game: $all"
    echo -e "\tcc -o game $all -lstdc++ -lglfw -framework OpenGL"
    for f in $(file_list); do
        make_cmd "$f"
    done
}

print_makefile > Makefile
