#!/usr/bin/env bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

BINARY_FILENAME='game'
BUNDLE_FILENAME='Game.app'
MAJOR_VERSION='0'
MINOR_VERSION='1'
BUNDLE_NAME='Galaxy Riders'
BUNDLE_ID='net.jaburns.www'

rm -rf "$BUNDLE_FILENAME"
mkdir -p "$BUNDLE_FILENAME/Contents/MacOS"
mkdir -p "$BUNDLE_FILENAME/Contents/Resources"

[[ ! -e "$BINARY_FILENAME" ]] && make
cp "$BINARY_FILENAME" "$BUNDLE_FILENAME/Contents/MacOS"
cp asset_src/osx_icons.icns "$BUNDLE_FILENAME/Contents/Resources"
cp -r res "$BUNDLE_FILENAME/Contents/MacOS"

get_external_lib_names() {
    otool -L "$1" \
        | grep -v "^[^\t]*:" \
        | grep -v '^\t/usr/lib' \
        | grep -v '^\t/System/Library' \
        | sed 's/	//;s/ (compatibility.*//'
}

remove_path_from_filename() {
    echo "$1" | sed 's:^.*/::'
}

get_external_lib_names "$BINARY_FILENAME" | while read -r lib; do
    cp "$lib" "$BUNDLE_FILENAME/Contents/MacOS"
    install_name_tool -change "$lib" "@executable_path/$(remove_path_from_filename $lib)" "$BUNDLE_FILENAME/Contents/MacOS/$BINARY_FILENAME"
done

cat >"$BUNDLE_FILENAME/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleGetInfoString</key>
    <string>$BUNDLE_NAME</string>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleName</key>
    <string>$BUNDLE_NAME</string>
    <key>CFBundleIconFile</key>
    <string>osx_icons.icns</string>
    <key>CFBundleShortVersionString</key>
    <string>$MAJOR_VERSION.$MINOR_VERSION</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>IFMajorVersion</key>
    <integer>$MAJOR_VERSION</integer>
    <key>IFMinorVersion</key>
    <integer>$MINOR_VERSION</integer>
</dict>
</plist>
EOF

cat >"$BUNDLE_FILENAME/Contents/MacOS/launcher" <<EOF
#!/usr/bin/env bash
cd "\${0%/*}"
./$BINARY_FILENAME
EOF
chmod +x "$BUNDLE_FILENAME/Contents/MacOS/launcher"
