#!/usr/bin/env bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

CC='cc'
CFLAGS='-std=c++14 -Iexternal/lodepng -Iexternal/glm -Iexternal/tinyxml2'

cpp_to_obj() {
    echo "$1" | sed 's/cpp$/o/'
}

make_cmd() {
    local obj_file="$(cpp_to_obj "$1")"
    $CC $CFLAGS -MM -MT "$obj_file" -c "$1"
    echo -e "\t$CC $CFLAGS -o $obj_file -c $1"
}

file_list() {
    find src/client src/shared -iname '*.cpp'
    echo external/lodepng/lodepng.cpp
    echo external/tinyxml2/tinyxml2.cpp
}

print_makefile() {
    local all=''
    for f in $(file_list); do
        all="$all $(cpp_to_obj $f)"
    done
    echo "game: $all"
    echo -e "\tcc -o game $all -lstdc++ -lglfw -framework OpenGL"

    for f in $(file_list); do
        make_cmd "$f"
    done

    echo '.PHONY: clean'
    echo -e "clean:\n\t find . -iname '*.o' | xargs rm && rm -f ./game"
}

print_makefile > Makefile
