#!/usr/bin/env bash

pushd external

    wget https://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0-win32.zip
    rm -rf glew-2.1.0
    unzip glew-2.1.0-win32.zip
    rm glew-2.1.0-win32.zip

    wget https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip
    rm -rf SDL2-2.0.5
    unzip SDL2-devel-2.0.5-VC.zip
    rm SDL2-devel-2.0.5-VC.zip

popd

cp external/glew-2.1.0/bin/Release/x64/glew32.dll .
cp external/SDL2-2.0.5/lib/x64/SDL2.dll .

pushd tools

    echo 'Building tool programs...'
    ./build

    echo 'Generating wireframe mesh data...'
    ./generate_wire_meshes

    echo 'Computing signed distance fields from sprites...'
    ./compute_sdfs

popd
