#!/usr/bin/env bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

CC='cc'
CFLAGS='-std=c++14 -I../external/lodepng -O3'

if [[ "$OSTYPE" == 'darwin'* ]]; then
    LDFLAGS='-lc++'
else
    LDFLAGS='-lstdc++'
fi

$CC -o tools *.cpp ../external/lodepng/lodepng.cpp $CFLAGS $LDFLAGS

[[ "$1" == 'run' ]] && ./tools
